intelligent github-fix

diff --git a/bin/github-fix b/bin/github-fix
--- a/bin/github-fix
+++ b/bin/github-fix
@@ -3,20 +3,29 @@ set -euo pipefail
 
 # intended to be called as first thing in a github workflow, before bin/github-checkout
 
+UID_COLON_GID="$(id -u -n):$(id -g -n)"
+
 # GITHUB_WORKSPACE owned by 1001:116, makes it impossible to write in the folder
-echo "Is GITHUB_WORKSPACE=${GITHUB_WORKSPACE} owned by 1001:116 ?"
-ls -la -d ${GITHUB_WORKSPACE}
-echo "Change ownership to $(id -u -n):$(id -g -n)."
-sudo chown $(id -u -n):$(id -g -n) ${GITHUB_WORKSPACE}
+# NOTE try GNU format, then BSD, then fail
+GITHUB_WORKSPACE_UID_COLON_GID=$(stat -c "%U:%G" ${GITHUB_WORKSPACE}) || \
+    GITHUB_WORKSPACE_UID_COLON_GID=$(stat -f "%Su:%Sg" ${GITHUB_WORKSPACE})
+[[ "${GITHUB_WORKSPACE_UID_COLON_GID}" = "${UID_COLON_GID}" ]] || {
+    echo "Changing ownership of GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
+    echo "owned by ${GITHUB_WORKSPACE_UID_COLON_GID} to ${UID_COLON_GID}."
+    sudo chown ${UID_COLON_GID} ${GITHUB_WORKSPACE}
+}
 
 # HOME set to /github/home, turns off sourcing ~/.profile, ~/.bash_profile, ~/.bashrc etc
 HOME_REAL=$(eval echo "~$(id -u -n)")
-echo "Is HOME=${HOME} set to /github/home?"
-echo "${HOME}"
-ls -la "${HOME}"
-echo "Change HOME to ${HOME_REAL} for $(id -u -n):$(id -g -n)."
-ls -la "${HOME_REAL}"
-echo "By adding to ${GITHUB_ENV}."
-touch ${GITHUB_ENV} || sudo touch ${GITHUB_ENV}
-ls -la ${GITHUB_ENV}
-echo "HOME=${HOME_REAL}" | sudo tee -a ${GITHUB_ENV}
+[[ "${HOME}" = "${HOME_REAL}" ]] || {
+    echo "Changing HOME=${HOME}"
+    echo "to ${HOME_REAL} for ${UID_COLON_GID}."
+    echo "${HOME}"
+    ls -la "${HOME}"
+    echo "${HOME_REAL}"
+    ls -la "${HOME_REAL}"
+    echo "By adding to ${GITHUB_ENV}."
+    touch ${GITHUB_ENV} || sudo touch ${GITHUB_ENV}
+    ls -la ${GITHUB_ENV}
+    echo "HOME=${HOME_REAL}" | sudo tee -a ${GITHUB_ENV}
+}
