pre-push hook: add info on skipping the hook

diff --git a/repo/dot.git/hooks/pre-push b/repo/dot.git/hooks/pre-push
--- a/repo/dot.git/hooks/pre-push
+++ b/repo/dot.git/hooks/pre-push
@@ -1,5 +1,14 @@
 #!/usr/bin/env bash
 
+function on_exit() {
+    [[ "$?" != "0" ]] || return
+
+    echo "[ERR ] pre-push hook failed."
+    echo "[INFO] If you want ignore the hook and push anyway, use 'git push --no-verify ...'."
+}
+
+trap on_exit EXIT
+
 SUPPORT_FIRECLOUD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../support-firecloud" && pwd)"
 source ${SUPPORT_FIRECLOUD_DIR}/sh/common.inc.sh
 
